package com.example.coderhack.dto;


import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.Max;
import lombok.Data;
import org.hibernate.validator.constraints.NotEmpty;

@Data
public class UserRequestDTO {

    @NotEmpty(message = "Username is required")
    private String username;

    @Min(value = 0, message = "Score must be greater than or equal to 0")
    @Max(value = 100, message = "Score must be less than or equal to 100")
    private int score;

    public UserRequestDTO(String username) {
        this.username = username;
        this.score =  0;
    }
}

/**
 *
 *
 * When creating a new user, the id is usually auto-generated by the database
 * Badges are often derived or computed based on the user’s score or other criteria. The client doesn't directly set these values during registration or update.
 */